// Shared data: mentors, applications, antoine detail
window.MENTORS = [
  {
    slug: "antoine-martin",
    initials: "AM",
    name: "Antoine Martin",
    headline: "Pitch investor + funding strategist",
    rating: 4.8,
    reviews: 47,
    classes: 12,
    location: "Paris · Lisbonne",
    category: "Business",
    skills: [
      { label: "Pitch investor", primary: true },
      { label: "Funding" },
      { label: "Public speaking" },
    ],
  },
  {
    slug: "marie-dupont",
    initials: "MD",
    name: "Marie Dupont",
    headline: "UI Designer + Webflow master",
    rating: 4.7,
    reviews: 38,
    classes: 9,
    location: "Bali",
    category: "Design",
    skills: [
      { label: "UI Design", primary: true },
      { label: "Figma" },
    ],
  },
  {
    slug: "david-cohen",
    initials: "DC",
    name: "David Cohen",
    headline: "Growth Marketing B2B",
    rating: 4.6,
    reviews: 52,
    classes: 15,
    location: "Tel Aviv",
    category: "Business",
    skills: [
      { label: "Growth B2B", primary: true },
      { label: "Lean Canvas" },
    ],
  },
  {
    slug: "sophie-bernard",
    initials: "SB",
    name: "Sophie Bernard",
    headline: "Lean Startup + Business Model Canvas",
    rating: 4.5,
    reviews: 29,
    classes: 7,
    location: "Mexico City",
    category: "Business",
    skills: [
      { label: "Lean Canvas", primary: true },
      { label: "Business model" },
    ],
  },
  {
    slug: "lucas-garcia",
    initials: "LG",
    name: "Lucas Garcia",
    headline: "Product Manager + UX research",
    rating: 4.3,
    reviews: 11,
    classes: 3,
    location: "Barcelone",
    category: "Design",
    skills: [
      { label: "UI Design", primary: true },
      { label: "Product" },
    ],
  },
  {
    slug: "claire-okonkwo",
    initials: "CO",
    name: "Claire Okonkwo",
    headline: "Frontend Architect · React, Next.js",
    rating: 4.9,
    reviews: 23,
    classes: 5,
    location: "Lagos · Lisbonne",
    category: "Tech",
    skills: [
      { label: "React avancé", primary: true },
      { label: "Next.js" },
      { label: "Perf" },
    ],
  },
];

window.ANTOINE = {
  ...window.MENTORS[0],
  bio: [
    "Ex-VC, 10 ans à accompagner des fondateurs vers leur première levée. J'aide mes apprenants à construire un narratif investor qui résiste au Q&A, à structurer leur deck pour donner envie en 2 minutes, et à comprendre les attentes réelles d'un fonds amorçage français.",
    "Mon approche est concrète : on travaille sur ton vrai deck, ta vraie traction, tes vrais chiffres. Pas de framework générique. À la fin de la classe, tu pitches pour de vrai devant 3 investisseurs partenaires de Hello Mira.",
    "Je vis entre Paris et Lisbonne depuis 2023. Mira Nomad m'a permis de continuer à mentorer pendant mes voyages — c'est pour ça que j'enseigne ici.",
  ],
  experience: [
    { range: "2022 — 2024", role: "Partner", company: "Eutopia Ventures", city: "Paris" },
    { range: "2018 — 2022", role: "Director Investments", company: "Daphni", city: "Paris" },
    { range: "2014 — 2018", role: "Associate", company: "Idinvest Partners", city: "Paris" },
  ],
  classOffers: [
    {
      title: "Pitcher pour lever 500 k€",
      price: "80 €",
      format: "Live hybride",
      capacity: "5 – 8 personnes",
      modules: "2 modules · 4 sessions",
      next: "Démarre le 3 juin",
    },
  ],
};

window.APPLICATIONS = [
  {
    id: "emma-rossi",
    initials: "ER",
    name: "Emma Rossi",
    headline: "Designer brand + content créatrice DTC",
    status: "submitted",
    when: "il y a 2 h",
    cvImported: false,
    bio:
      "10 ans en design de marque côté DTC. Ex-Stripe (brand), puis founder de Brand Studio — agence à 200 k€ ARR, équipe de 4 personnes. J'accompagne des nomades qui veulent construire une marque de produit qui se vend sans pub. Ce que j'enseigne : visual identity, brand voice, premier site qui convertit, et surtout comment ne pas avoir l'air d'un dropshipper. Format préféré : mini-cohorte de 4-6, 6 semaines, output final = brand kit + site live.",
    skillsProposed: [
      { label: "Brand identity", primary: true },
      { label: "DTC" },
      { label: "Webflow" },
      { label: "Content visuel" },
    ],
    experience: [
      { range: "2022 — 2025", role: "Founder", company: "Brand Studio", city: "Lisbonne" },
      { range: "2019 — 2022", role: "Brand Designer", company: "Stripe", city: "Dublin" },
      { range: "2016 — 2019", role: "Designer", company: "BETC", city: "Paris" },
    ],
    motivation:
      "J'ai été nomade 4 ans avant d'avoir un revenu stable. Personne ne m'a dit qu'on pouvait construire une marque depuis un café à Canggu. Aujourd'hui je veux raccourcir ce chemin pour d'autres — et Mira est la seule plateforme qui parle vraiment aux nomades, pas aux étudiants en management.",
    cv: { name: "emma-rossi-cv.pdf", size: "412 Ko", aiExtracted: true },
    masterclass: {
      title: "Construire ta brand DTC en 30 jours",
      description: "De zéro à une identité de marque cohérente : positioning, naming, design system minimaliste. Pour fondateurs solo qui lancent leur première DTC.",
      origin: "ai-suggested",
      skills: [{ label: "Brand identity", primary: true }, { label: "Content strategy" }],
      params: {
        duration: "18 h",
        sessions: "6 sessions de 3 h",
        format: "Hybride",
        cohort: "4 – 6 personnes",
        price: "1 200 € / apprenant",
        cities: ["Lisbonne", "Paris"],
      },
      demand: { kind: "hot", text: "31 nomades cherchent cette skill" },
    },
  },
  {
    id: "nathan-kim",
    initials: "NK",
    name: "Nathan Kim",
    headline: "Tech Lead → CTO startup",
    status: "submitted",
    when: "il y a 1 h",
    cvImported: true,
    bio: "10 ans tech, ex-Doctolib (Tech Lead pendant 3 ans), maintenant CTO d'une seed B2B health. Veut transmettre le saut de Senior IC → engineering manager → CTO sans se cramer.",
    skillsProposed: [
      { label: "Engineering management", primary: true },
      { label: "Hiring tech" },
      { label: "Scaling teams" },
    ],
    experience: [],
    motivation: "",
    cv: { name: "nathan-kim-cv.pdf", size: "780 Ko", aiExtracted: true },
  },
  {
    id: "chloe-dubois",
    initials: "CD",
    name: "Chloé Dubois",
    headline: "Sales B2B + closing négociation",
    status: "inreview",
    when: "il y a 3 j",
    cvImported: false,
    bio: "50 M€ closed sur 7 ans, ex-Salesforce et 2 startups Series B. Mentore déjà des SDR sur Slack depuis 1 an.",
    skillsProposed: [
      { label: "Closing B2B", primary: true },
      { label: "Négociation" },
    ],
    experience: [],
    motivation: "",
    cv: { name: "chloe-dubois-cv.pdf", size: "521 Ko", aiExtracted: false },
  },
  {
    id: "paul-weiss",
    initials: "PW",
    name: "Paul Weiss",
    headline: "Coach perso",
    status: "rejected",
    when: "il y a 5 j",
    cvImported: false,
    bio: "Coach de vie, certifié ICF. Veut aider les nomades à \"trouver leur ikigai\".",
    skillsProposed: [
      { label: "Coaching de vie", primary: true },
    ],
    experience: [],
    motivation: "",
    cv: null,
    rejectedReason: "Expertise insuffisamment documentée — pas de track-record sur lequel s'appuyer.",
  },
];

window.STATUS_LABEL = {
  submitted: "Submitted",
  inreview: "En examen",
  validated: "Validated",
  rejected: "Rejected",
};
